name: 01 - Building Blocks
on: [push, workflow_dispatch]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
      - id: Say hello
        run: echo "Hello World!"
  job-2:
    runs-on: ubuntu-latest
    steps: 
      - id: Failed step
        run: |
          echo "I"
          echo " will fail!"
          exit 1
      - id: Say goodbye
        run: echo "Goodbye!"