name: 01 - Building Blocks
on: [workflow_dispatch]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
      - name: Say hello
        run: echo "Hello World!"
  job-2:
    runs-on: ubuntu-latest
    steps: 
      - name: Failed step
        run: |
          echo "I"
          echo " will fail!"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"