name: 04 - Using Actions
on: 
  - push

jobs:
    build:
        runs-on: ubuntu
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                path: main
          - name: Printing Folders
            run: sh "ls -laR"

