name: 04 - Using Actions
on: 
  - push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                path: main
          - name: Setup Node
            uses: actions/setup-node@v4
            with:
                node-version: 20.*
          - name: Install Dependencies
            run: npm ci

