name: 08 - Using variables

on:
    push:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Print Env Var
              env: 
                STEP_VAR: "I am a step env var"
                step_var2: "I am another step env var"
              run: |
                echo "step env var: ${{ env.STEP_VAR}}"
                echo "step env var 2: $step_var2"


