name: 17 - 2 - Custom Actions - Composite
run-name:  17 - 2 - Custom Actions - JS

on:
  workflow_dispatch:


jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for Dependency updates
        uses: ./.github/actions/composite-cache-deps

        